import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import Header from "@/components/layout/Header";

import { SocketProvider } from "@/context/SocketContext";
import QueryProvider from "@/context/QueryProvider";
import AuthProvider from "@/context/AuthProvider"; 

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Script
          src="https://accounts.google.com/gsi/client"
          strategy="afterInteractive"
        />

        <QueryProvider>
          <AuthProvider> 
            <SocketProvider>
              <Header />
              <div className="pt-16" />
              {children}
            </SocketProvider>
          </AuthProvider>
        </QueryProvider>

      </body>
    </html>
  );
}